#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         B-Keywords
version:      0.06
version_from: lib/B/Keywords.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.10_07
